<?php
/**
 * Override native media behaviour.
 *
 * @package wordpress-thumbor
 */

namespace Eighteen73\Thumbor;

/**
 * Plugin singleton class.
 */
class MediaOverrides {
	/**
	 * Oh look, a singleton!
	 *
	 * @var Thumbor|null
	 */
	private static $instance = null;

	private $sizes = [];

	/**
	 * Singleton implementation
	 *
	 * @return object
	 */
	public static function instance() {

		if ( ! defined( 'THUMBOR_URL' ) || empty( THUMBOR_URL ) ) {
			return;
		}

		if ( ! is_a( self::$instance, __CLASS__ ) ) {
			$class          = get_called_class();
			self::$instance = new $class();
			self::$instance->setup();
		}

		return self::$instance;
	}

	/**
	 * Silence is golden.
	 */
	private function __construct() {}

	/**
	 * Register actions and filters, but only if basic Thumbor functions are available.
	 * The basic functions are found in ./wordpress-thumbor.php.
	 *
	 * @uses add_action, add_filter
	 * @return null
	 */
	private function setup() {

		if ( ! function_exists( 'thumbor_url' ) ) {
			return;
		}

		// Capture sizes before removal
		add_filter( 'intermediate_image_sizes_advanced', [ $this, 'capture_sizes' ], 1, 1 );

		// Don't scale down big images
		add_filter( 'big_image_size_threshold', [ $this, 'image_threshold' ], 999, 1 );

		// Don't resize any images
		add_filter( 'intermediate_image_sizes_advanced', [ $this, 'prevent_resizing' ], 10, 5 );

		// Add metadata for sizes after upload
        add_filter( 'wp_generate_attachment_metadata', [ $this, 'generate_metadata' ], 10, 2 );
	}

	/**
     * Capture the sizes before they are removed.
     *
     * @param array $sizes The registered image sizes.
     * @return array Unchanged sizes for now.
     */
    public function capture_sizes( $sizes ) {
        $this->sizes = $sizes; // Save the sizes for later use.
        return $sizes;
    }

	/**
	 * Prevents any images from being automatically created.
	 *
	 * @param int $threshold The threshold value in pixels.
	 *
	 * @return bool|int The new “big image” threshold value.
	 */
	public static function image_threshold( $threshold ) {

		if ( ! defined( 'THUMBOR_UPLOAD_IMAGE_THRESHOLD' ) ) {
			return $threshold;
		}

		if ( THUMBOR_UPLOAD_IMAGE_THRESHOLD === false ) {
			return false;
		} elseif ( is_int( THUMBOR_UPLOAD_IMAGE_THRESHOLD ) ) {
			return THUMBOR_UPLOAD_IMAGE_THRESHOLD;
		}

		return $threshold;
	}

	/**
	 * Prevents any images from being automatically created.
	 *
	 * @param array $sizes Associative array of image sizes to be created.
	 * @param array $image_meta The image meta data: width, height, file, sizes, etc.
	 *
	 * @return array Associative array of image sizes to be created.
	 */
	public static function prevent_resizing( $sizes, $image_meta ) {
		return [];
	}

	/**
     * Generate metadata for the stored sizes after the image is uploaded.
     *
     * @param array $metadata The metadata generated by WordPress.
     * @param int   $attachment_id The attachment ID of the uploaded image.
     * @return array Modified metadata including size data.
     */
    public function generate_metadata( $metadata, $attachment_id ) {
        // Get the original file path
        $file = get_attached_file( $attachment_id );
        if ( ! file_exists( $file ) ) {
            return $metadata; // Exit if file doesn't exist
        }

        // Get the original image dimensions
        $image_size = getimagesize( $file );
        if ( ! $image_size ) {
            return $metadata; // Exit if file is invalid
        }

        $original_width  = $image_size[0];
        $original_height = $image_size[1];

        // Populate the metadata for each captured size
        foreach ( $this->sizes as $size => $size_data ) {
            $width  = min( $size_data['width'], $original_width );
            $height = min( $size_data['height'], $original_height );

            // Add size metadata
            $metadata['sizes'][ $size ] = [
                'file'      => wp_basename( $file ), // Use the original filename
                'width'     => $width,
                'height'    => $height,
                'mime-type' => mime_content_type( $file ),
            ];
        }

        return $metadata;
    }
}
